# -*- coding: utf-8 -*-
"""AI_LOGIC( Problem1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJok4Q7jIyeRK4kGjr2YWeaHJ4KIKGBH
"""

n = int(input())

data = []

for i in range(n):
    x, y = map(int, input().split())
    data.append([x, y])

data.sort()

result = []

for x, y in data:

    if len(result) == 0:
        result.append([x, y])

    elif x <= result[-1][1]:
        if y > result[-1][1]:
            result[-1][1] = y

    else:
        result.append([x, y])

for x, y in result:
    print(x, y)

