# -*- coding: utf-8 -*-
"""AI_LOGIC( Problem3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJok4Q7jIyeRK4kGjr2YWeaHJ4KIKGBH
"""

n = int(input())
first = list(map(int, input().split()))

m = int(input())
second = list(map(int, input().split()))

answer = []

i = 0
j = 0
carry = 0

while i < n or j < m or carry:

    if i < n:
        a = first[i]
    else:
        a = 0

    if j < m:
        b = second[j]
    else:
        b = 0

    total = a + b + carry

    digit = total % 10
    carry = total // 10

    answer.append(digit)

    i += 1
    j += 1

print(*answer)

