# -*- coding: utf-8 -*-
"""AI Logics – Technical Assessment (shaik_ruhulameen).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT62XbUoVjRGkDx8Rd1e6Wz4QIkg_HXJ

#1)question-1
"""

n = int(input())

data = []

for i in range(n):
    x, y = map(int, input().split())
    data.append([x, y])

data.sort()

result = []

for x, y in data:

    if len(result) == 0:
        result.append([x, y])

    elif x <= result[-1][1]:
        if y > result[-1][1]:
            result[-1][1] = y

    else:
        result.append([x, y])

for x, y in result:
    print(x, y)

"""#2)question-2"""

n = int(input())
a = list(map(int, input().split()))
k = int(input())

ans = 0
pos = 1

for i in range(n):
    high = a[i]
    low = a[i]

    for j in range(i, n):
        if a[j] > high:
            high = a[j]

        if a[j] < low:
            low = a[j]

        if high - low <= k:
            size = j - i + 1

            if size > ans:
                ans = size
                pos = i + 1
        else:
            break

print(ans, pos)

"""#3)question-3"""

n = int(input())
first = list(map(int, input().split()))

m = int(input())
second = list(map(int, input().split()))

answer = []

i = 0
j = 0
carry = 0

while i < n or j < m or carry:

    if i < n:
        a = first[i]
    else:
        a = 0

    if j < m:
        b = second[j]
    else:
        b = 0

    total = a + b + carry

    digit = total % 10
    carry = total // 10

    answer.append(digit)

    i += 1
    j += 1

print(*answer)

