# -*- coding: utf-8 -*-
"""AI_LOGIC( Problem2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJok4Q7jIyeRK4kGjr2YWeaHJ4KIKGBH
"""

n = int(input())
a = list(map(int, input().split()))
k = int(input())

ans = 0
pos = 1

for i in range(n):
    high = a[i]
    low = a[i]

    for j in range(i, n):
        if a[j] > high:
            high = a[j]

        if a[j] < low:
            low = a[j]

        if high - low <= k:
            size = j - i + 1

            if size > ans:
                ans = size
                pos = i + 1
        else:
            break

print(ans, pos)

